// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW4g_jYWlysfwq6PAYdUz5qFwfcMwjw5o',
    appId: '1:457032359457:android:f7c1f72eab205aecb0cd60',
    messagingSenderId: '457032359457',
    projectId: 'eduflex-24b2e',
    storageBucket: 'eduflex-24b2e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSqB18oLGfLCJT667R2u-_DIJ2Bl85RRc',
    appId: '1:457032359457:ios:8915d157d3535264b0cd60',
    messagingSenderId: '457032359457',
    projectId: 'eduflex-24b2e',
    storageBucket: 'eduflex-24b2e.appspot.com',
    androidClientId: '457032359457-2t1g99k8fvhtfbigda25pn4bokrbh3ts.apps.googleusercontent.com',
    iosClientId: '457032359457-6fhgu495mml2nghg7ra63a385lpkjkep.apps.googleusercontent.com',
    iosBundleId: 'com.example.eduflex',
  );
}
